#!/usr/bin/env python
"""Generate the code-grounded reference pages for the OEDISI docs.

This script produces four MyST pages directly from the live code so they can
never drift from the implementation:

* ``advanced/cli.md``          — from Click introspection of the ``oedisi`` CLI
* ``advanced/api.md``          — from griffe docstrings + Pydantic model fields
* ``advanced/data-types.md``   — from ``oedisi.types.data_types``
* ``beginner/component-catalog.md`` — from the frontend registry + each
  component's ``component_definition.json``

Run it from anywhere::

    python docs/tools/generate.py                 # regenerate all pages
    python docs/tools/generate.py --check         # fail if pages are stale
    python docs/tools/generate.py --targets cli api data-types

The component catalog needs the sibling ``oedisi-components`` and
``oedisi-frontend-app`` repositories; the other three pages need only the
installed ``oedisi`` package.
"""

from __future__ import annotations

import argparse
import inspect
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

DOCS = Path(__file__).resolve().parents[1]
REPO_ROOT = DOCS.parent
WORKSPACE = REPO_ROOT.parent

GENERATED_NOTE = (
    "% DO NOT EDIT — generated by docs/tools/generate.py from the live code.\n"
    "% Re-run `python docs/tools/generate.py` after changing the CLI, the\n"
    "% `oedisi` API, the data types, or the component registry.\n"
)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def clean_type(annotation: Any) -> str:
    """Render a type annotation without module noise."""
    if annotation is inspect.Signature.empty or annotation is None:
        return ""
    s = annotation if isinstance(annotation, str) else _annotation_repr(annotation)
    s = s.replace("typing.", "")
    s = re.sub(r"<class '([^']+)'>", r"\1", s)
    s = re.sub(r"ForwardRef\('([^']+)'\)", r"\1", s)
    # Make object reprs reproducible: drop memory addresses and simplify callables.
    s = re.sub(r"\s+at\s+0x[0-9a-fA-F]+", "", s)
    s = re.sub(r"<(?:function|built-in function|method)\s+([\w.]+)[^>]*>", r"\1", s)
    # Strip dotted module prefixes: foo.bar.Baz -> Baz
    s = re.sub(r"(?:[A-Za-z_][\w]*\.)+([A-Za-z_]\w*)", r"\1", s)
    s = s.replace("NoneType", "None")
    return s.strip()


def _annotation_repr(annotation: Any) -> str:
    try:
        return str(annotation)
    except Exception:  # pragma: no cover - defensive
        return repr(annotation)


def md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _griffe_package():
    import griffe

    if not hasattr(_griffe_package, "_cache"):
        _griffe_package._cache = griffe.load(
            "oedisi", submodules=True, allow_inspection=True
        )
    return _griffe_package._cache


def griffe_doc(qualname: str, live_obj: Any = None) -> str:
    """Return a docstring via griffe, falling back to ``inspect``."""
    try:
        obj = _griffe_package()
        for part in qualname.split("."):
            obj = obj[part]
        if obj.docstring and obj.docstring.value:
            return inspect.cleandoc(obj.docstring.value)
    except Exception:
        pass
    if live_obj is not None:
        return inspect.getdoc(live_obj) or ""
    return ""


# --------------------------------------------------------------------------- #
# Pydantic rendering
# --------------------------------------------------------------------------- #
def is_pydantic_model(obj: Any) -> bool:
    try:
        from pydantic import BaseModel

        return isinstance(obj, type) and issubclass(obj, BaseModel)
    except Exception:
        return False


def field_rows(model: type, only_own: bool = False) -> list[tuple[str, str, str, str]]:
    """Return (name, type, required/default, description) rows for a model."""
    from pydantic import BaseModel

    parent_fields: set[str] = set()
    if only_own:
        for base in model.__bases__:
            if is_pydantic_model(base) and base is not BaseModel:
                parent_fields |= set(getattr(base, "model_fields", {}))

    rows: list[tuple[str, str, str, str]] = []
    for fname, field in model.model_fields.items():
        if only_own and fname in parent_fields:
            continue
        typ = clean_type(field.annotation)
        if field.is_required():
            req = "**required**"
        else:
            default = field.default
            req = f"`{default!r}`" if default is not None else "`None`"
        desc = md_escape(field.description or "")
        rows.append((fname, typ, req, desc))
    return rows


def render_field_table(rows: list[tuple[str, str, str, str]]) -> str:
    if not rows:
        return ""
    out = ["| Field | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for name, typ, req, desc in rows:
        out.append(f"| `{name}` | `{typ}` | {req} | {desc} |")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- #
# Page: CLI
# --------------------------------------------------------------------------- #
def _clean_cli_help(cmd) -> str:
    """User-facing help for a Click command, without the autodoc tail.

    Click hides everything after a form-feed in help output; some docstrings
    encode it literally as ``\f``. We also drop any trailing numpydoc
    ``Parameters`` section so the page is deterministic across Click versions.
    """
    text = cmd.help or ""
    for sep in ("\x0c", "\\f"):
        text = text.split(sep, 1)[0]
    text = re.split(r"\n[ \t]*Parameters[ \t]*\n[ \t]*-{3,}", text)[0]
    return inspect.cleandoc(text).strip()


def render_cli() -> str:
    import click

    from oedisi.tools import cli

    lines = [
        "---",
        "title: Command-line interface",
        "description: Every oedisi command and option, generated from the CLI.",
        "---",
        "",
        GENERATED_NOTE,
        "# Command-line interface",
        "",
        "The `oedisi` command-line tool builds and runs simulations. Installing the",
        "`oedisi` package puts it on your `PATH`; run `oedisi --help` to see the same",
        "summary reproduced here.",
        "",
        "```text",
        "Usage: oedisi [OPTIONS] COMMAND [ARGS]...",
        "```",
        "",
        "## Commands",
        "",
    ]

    # Summary table
    lines.append("| Command | Summary |")
    lines.append("| --- | --- |")
    for name, cmd in sorted(cli.commands.items()):
        summary = md_escape(_clean_cli_help(cmd).split("\n", 1)[0])
        lines.append(f"| [`oedisi {name}`](#cli-{slug(name)}) | {summary} |")
    lines.append("")

    for name, cmd in sorted(cli.commands.items()):
        lines.append(f"(cli-{slug(name)})=")
        lines.append(f"### `oedisi {name}`")
        lines.append("")
        help_body = _clean_cli_help(cmd)
        if help_body:
            lines.append(help_body)
            lines.append("")
        lines.append("```text")
        lines.append(f"Usage: oedisi {name} [OPTIONS]")
        lines.append("```")
        lines.append("")

        opts = [p for p in cmd.params if isinstance(p, click.Option)]
        opts = [p for p in opts if p.name != "help"]
        if opts:
            lines.append("| Option | Type | Default | Description |")
            lines.append("| --- | --- | --- | --- |")
            for p in opts:
                flags = "`" + "`, `".join(p.opts + p.secondary_opts) + "`"
                if p.is_flag:
                    typ = "flag"
                else:
                    typ = getattr(p.type, "name", "") or ""
                if p.required:
                    default = "**required**"
                elif p.default is not None and p.default != ():
                    default = f"`{p.default!r}`"
                else:
                    default = "—"
                desc = md_escape(p.help or "")
                lines.append(f"| {flags} | {typ} | {default} | {desc} |")
            lines.append("")

    lines.append(":::{seealso}")
    lines.append("Building blocks these commands operate on: the")
    lines.append("[Python API](api.md) and the [multi-container workflow](multicontainer.md).")
    lines.append(":::")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Page: API
# --------------------------------------------------------------------------- #
API_SECTIONS = [
    (
        "Component framework",
        "oedisi.componentframework.system_configuration",
        "componentframework.system_configuration",
        [
            "WiringDiagram",
            "Component",
            "Link",
            "Port",
            "AnnotatedType",
            "ComponentStruct",
            "ComponentType",
            "ComponentCapabilities",
            "Federate",
            "RunnerConfig",
            "generate_runner_config",
            "initialize_federates",
        ],
    ),
    (
        "Basic components",
        "oedisi.componentframework.basic_component",
        "componentframework.basic_component",
        ["ComponentDescription", "component_from_json", "basic_component"],
    ),
]


def render_api() -> str:
    import importlib

    lines = [
        "---",
        "title: Python API reference",
        "description: Public classes and functions of the oedisi package.",
        "---",
        "",
        GENERATED_NOTE,
        "# Python API reference",
        "",
        "The `oedisi` package exposes the component framework used to describe and",
        "compile co-simulations. The reference below is generated from the package's",
        "own docstrings and Pydantic models. For the data models exchanged between",
        "components see [Data types](data-types.md); for the CLI see the",
        "[command-line interface](cli.md).",
        "",
    ]

    for title, module_path, griffe_prefix, names in API_SECTIONS:
        module = importlib.import_module(module_path)
        lines.append(f"## {title}")
        lines.append("")
        lines.append(f"Module: `{module_path}`")
        lines.append("")
        for objname in names:
            obj = getattr(module, objname, None)
            if obj is None:
                print(f"[skip] {module_path}.{objname} not found", file=sys.stderr)
                continue
            anchor = slug(objname)
            lines.append(f"(api-{anchor})=")
            kind = "class" if isinstance(obj, type) else "function"
            lines.append(f"### `{objname}` ({kind})")
            lines.append("")
            if isinstance(obj, type):
                # Only the class's own docstring — never an inherited one.
                own = obj.__dict__.get("__doc__")
                doc = griffe_doc(f"{griffe_prefix}.{objname}") or (
                    inspect.cleandoc(own) if own else ""
                )
            else:
                doc = griffe_doc(f"{griffe_prefix}.{objname}", obj)
                try:
                    sig = clean_type(str(inspect.signature(obj)))
                    lines.append(f"```python\n{objname}{sig}\n```")
                    lines.append("")
                except (TypeError, ValueError):
                    pass
            if doc:
                lines.append(_docstring_to_md(doc))
                lines.append("")
            if is_pydantic_model(obj):
                rows = field_rows(obj, only_own=False)
                table = render_field_table(rows)
                if table:
                    lines.append("**Fields**")
                    lines.append("")
                    lines.append(table)
    return "\n".join(lines)


def _docstring_to_md(doc: str) -> str:
    """Render a NumPy-style docstring body safely for MyST.

    We keep it simple and faithful: emit the docstring inside a fenced block if
    it contains section underlines, otherwise as prose.
    """
    if re.search(r"\n-{3,}\n", "\n" + doc):
        return f"```text\n{doc.strip()}\n```"
    return doc.strip()


# --------------------------------------------------------------------------- #
# Page: Data types
# --------------------------------------------------------------------------- #
def documented_data_types() -> list[tuple[str, type]]:
    """The data-type models to document — the exact set the catalog links to.

    Includes concrete models defined in the module *and* the ``RootModel`` list
    wrappers (e.g. ``CommandList``) that live in the module namespace but whose
    ``__module__`` is pydantic's.
    """
    import oedisi.types.data_types as dt
    from pydantic import BaseModel, RootModel

    pairs: list[tuple[str, type]] = []
    for name, obj in vars(dt).items():
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            continue
        if obj in (BaseModel, RootModel) or not name[:1].isupper():
            continue
        pairs.append((name, obj))
    return pairs


def render_data_types() -> str:
    from pydantic import RootModel

    pairs = documented_data_types()
    module_names = {name for name, _ in pairs}

    lines = [
        "---",
        "title: Data types",
        "description: The oedisi.types models components use to exchange data.",
        "---",
        "",
        GENERATED_NOTE,
        "# Data types",
        "",
        "Components exchange typed values defined as [Pydantic](https://docs.pydantic.dev)",
        "models in `oedisi.types.data_types`. A port's `type` in a",
        "`component_definition.json` refers to one of the models below. Many concrete",
        "types are thin subclasses that inherit their fields from a base array type.",
        "",
        "## Summary",
        "",
        "| Type | Inherits |",
        "| --- | --- |",
    ]
    for name, m in pairs:
        base = m.__bases__[0].__name__
        base_link = (
            f"[`{base}`](#datatype-{slug(base)})"
            if base in module_names
            else f"`{base}`"
        )
        lines.append(f"| [`{name}`](#datatype-{slug(name)}) | {base_link} |")
    lines.append("")

    for name, m in pairs:
        base = m.__bases__[0].__name__
        lines.append(f"(datatype-{slug(name)})=")
        lines.append(f"### {name}")
        lines.append("")
        if base in module_names:
            lines.append(f"Inherits [`{base}`](#datatype-{slug(base)}).")
        else:
            lines.append(f"Inherits `{base}`.")
        lines.append("")
        if issubclass(m, RootModel):
            root_ann = clean_type(m.model_fields["root"].annotation)
            lines.append(f"A list wrapper around `{root_ann}`.")
            lines.append("")
            continue
        if m.__module__ == "oedisi.types.data_types":
            own_doc = m.__dict__.get("__doc__")
            if own_doc:
                lines.append(inspect.cleandoc(own_doc).strip())
                lines.append("")
        table = render_field_table(field_rows(m, only_own=True))
        if table:
            lines.append("**Fields**")
            lines.append("")
            lines.append(table)
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Page: Component catalog
# --------------------------------------------------------------------------- #
def _resolve_registry(registry: Path, components: Path) -> dict[str, Path]:
    raw = json.loads(registry.read_text())
    resolved: dict[str, Path] = {}
    for display, path in raw.items():
        p = path.replace("${OEDISI_COMPONENTS}", str(components))
        resolved[display] = Path(p)
    return resolved


def _first_paragraph(readme: Path) -> str:
    para: list[str] = []
    for line in readme.read_text(errors="ignore").splitlines():
        s = line.strip()
        if not s:
            if para:
                break
            continue
        if s.startswith("#"):
            if para:
                break
            continue
        if s.startswith(("![", "[!", "<", "|", "```", "=", "-")):
            continue
        para.append(s)
    text = " ".join(para)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)  # unwrap links
    return md_escape(text)[:320]


def _component_description(def_path: Path) -> str:
    d = def_path.parent
    for _ in range(3):
        readme = d / "README.md"
        if readme.exists():
            desc = _first_paragraph(readme)
            if desc:
                return desc
        d = d.parent
    return ""


def render_catalog(registry: Path, components: Path) -> str:
    known_types = {name for name, _ in documented_data_types()}

    entries = _resolve_registry(registry, components)

    def type_cell(t: str) -> str:
        if not t:
            return "—"
        if t in known_types:
            return f"[`{t}`](../advanced/data-types.md#datatype-{slug(t)})"
        return f"`{t}`"

    lines = [
        "---",
        "title: Component catalog",
        "description: Reference of the components available in the OEDISI UI.",
        "---",
        "",
        GENERATED_NOTE,
        "# Component catalog",
        "",
        "These are the components registered with the web app. Each is a HELICS",
        "federate that consumes (`subscribes`) and produces (`publishes`) the typed",
        "[data types](../advanced/data-types.md) listed below. The **name** is what you",
        "see in the designer palette; the **folder** is where its code lives in",
        "`oedisi-components`.",
        "",
        "## All components",
        "",
        "| Component | Folder | Subscribes | Publishes |",
        "| --- | --- | --- | --- |",
    ]

    details: list[str] = []
    for display in sorted(entries):
        def_path = entries[display]
        if not def_path.exists():
            continue
        try:
            defn = json.loads(def_path.read_text())
        except Exception:
            continue
        directory = defn.get("directory") or def_path.parent.name
        din = defn.get("dynamic_inputs", []) or []
        dout = defn.get("dynamic_outputs", []) or []
        sin = defn.get("static_inputs", []) or []
        lines.append(
            f"| [{display}](#component-{slug(display)}) | `{directory}` | "
            f"{len(din)} | {len(dout)} |"
        )

        details.append(f"(component-{slug(display)})=")
        details.append(f"## {display}")
        details.append("")
        details.append(f"Folder: `{directory}`")
        details.append("")
        desc = _component_description(def_path)
        if desc:
            details.append(desc)
            details.append("")
        if sin:
            details.append("**Configuration** (`static_inputs`)")
            details.append("")
            details.append("| Port | Type |")
            details.append("| --- | --- |")
            for port in sin:
                details.append(
                    f"| `{port.get('port_id', '')}` | {type_cell(port.get('type', ''))} |"
                )
            details.append("")
        if din:
            details.append("**Subscribes** (`dynamic_inputs`)")
            details.append("")
            details.append("| Port | Type | Optional |")
            details.append("| --- | --- | --- |")
            for port in din:
                opt = "yes" if port.get("optional") else ""
                details.append(
                    f"| `{port.get('port_id', '')}` | {type_cell(port.get('type', ''))} | {opt} |"
                )
            details.append("")
        if dout:
            details.append("**Publishes** (`dynamic_outputs`)")
            details.append("")
            details.append("| Port | Type |")
            details.append("| --- | --- |")
            for port in dout:
                details.append(
                    f"| `{port.get('port_id', '')}` | {type_cell(port.get('type', ''))} |"
                )
            details.append("")

    lines.append("")
    lines.extend(details)
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def build_pages(registry: Path, components: Path, targets: list[str]) -> dict[Path, str]:
    pages: dict[Path, str] = {}
    if "cli" in targets:
        pages[DOCS / "advanced" / "cli.md"] = render_cli()
    if "api" in targets:
        pages[DOCS / "advanced" / "api.md"] = render_api()
    if "data-types" in targets:
        pages[DOCS / "advanced" / "data-types.md"] = render_data_types()
    if "catalog" in targets:
        if registry.exists() and components.exists():
            pages[DOCS / "beginner" / "component-catalog.md"] = render_catalog(
                registry, components
            )
        else:
            print(
                f"[skip] catalog: registry ({registry}) or components ({components}) "
                "not found — skipping.",
                file=sys.stderr,
            )
    return pages


def main() -> int:
    default_registry = Path(
        os.environ.get(
            "OEDISI_FRONTEND_REGISTRY",
            WORKSPACE / "oedisi-frontend-app" / "server" / "components.json",
        )
    )
    default_components = Path(
        os.environ.get("OEDISI_COMPONENTS", WORKSPACE / "oedisi-components" / "Components")
    )

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=default_registry)
    parser.add_argument("--components", type=Path, default=default_components)
    parser.add_argument(
        "--targets",
        nargs="+",
        default=["cli", "api", "data-types", "catalog"],
        choices=["cli", "api", "data-types", "catalog"],
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any generated page is out of date.",
    )
    args = parser.parse_args()

    pages = build_pages(args.registry, args.components, args.targets)

    stale: list[Path] = []
    for path, content in pages.items():
        content = content.rstrip() + "\n"
        if args.check:
            current = path.read_text() if path.exists() else ""
            if current != content:
                stale.append(path)
        else:
            path.write_text(content)
            print(f"[write] {path.relative_to(REPO_ROOT)}")

    if args.check and stale:
        print("Stale generated pages (run docs/tools/generate.py):", file=sys.stderr)
        for path in stale:
            print(f"  - {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
